<?xml version="1.0" encoding="utf-8"?>
<xliff xmlns="urn:oasis:names:tc:xliff:document:1.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.2" xsi:schemaLocation="urn:oasis:names:tc:xliff:document:1.2 xliff-core-1.2-transitional.xsd">
  <file datatype="xml" original="SEHException.xml" source-language="en-US" target-language="ko-KR">
    <header>
      <tool tool-id="mdxliff" tool-name="mdxliff" tool-version="1.0-15c36f0" tool-company="Microsoft" />
      <xliffext:skl_file_name xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">02cd5861-7ce2-4a82-b358-31f8435a0ac52006f6528910fbef9742e14057a3aeaaabd43cff.skl</xliffext:skl_file_name>
      <xliffext:version xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">1.2</xliffext:version>
      <xliffext:ms.openlocfilehash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">2006f6528910fbef9742e14057a3aeaaabd43cff</xliffext:ms.openlocfilehash>
      <xliffext:ms.sourcegitcommit xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">d31dc2ede16f6f7bc64e90d9f897ff54c4e3869b</xliffext:ms.sourcegitcommit>
      <xliffext:ms.lasthandoff xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">04/03/2018</xliffext:ms.lasthandoff>
      <xliffext:moniker_ids xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">netcore-1.0,netcore-1.1,netcore-2.0,netcore-2.1,netframework-4.5.1,netframework-4.5.2,netframework-4.5,netframework-4.6.1,netframework-4.6.2,netframework-4.6,netframework-4.7.1,netframework-4.7,netstandard-1.1,netstandard-1.2,netstandard-1.3,netstandard-1.4,netstandard-1.5,netstandard-1.6,netstandard-2.0,xamarinandroid-7.1,xamarinios-10.8,xamarinmac-3.0</xliffext:moniker_ids>
    </header>
    <body>
      <group id="content" extype="content">
        <trans-unit id="101" translate="yes" xml:space="preserve" uid="T:System.Runtime.InteropServices.SEHException">
          <source>Represents structured exception handling (SEH) errors.</source>
          <target state="translated">SEH(구조적 예외 처리기) 오류를 나타냅니다.</target>       </trans-unit>
        <trans-unit id="102" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Runtime.InteropServices.SEHException">
          <source>The <ph id="ph1">&lt;xref:System.Runtime.InteropServices.SEHException&gt;</ph> class handles SEH errors that are thrown from unmanaged code, but that have not been mapped to another .NET Framework exception.</source>
          <target state="translated"><ph id="ph1">&lt;xref:System.Runtime.InteropServices.SEHException&gt;</ph> 클래스 SEH 오류 비관리 코드에서 throw 하는 있지만 있는 매핑되지 않은 다른.NET Framework 예외를 처리 합니다.</target>       </trans-unit>
        <trans-unit id="103" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Runtime.InteropServices.SEHException">
          <source>The <ph id="ph1">&lt;xref:System.Runtime.InteropServices.SEHException&gt;</ph> class also corresponds to the <ph id="ph2">`HRESULT`</ph> <ph id="ph3">`E_FAIL`</ph> (0x80004005).</source>
          <target state="translated"><ph id="ph1">&lt;xref:System.Runtime.InteropServices.SEHException&gt;</ph> 클래스에도 해당 하는 <ph id="ph2">`HRESULT`</ph> <ph id="ph3">`E_FAIL`</ph> (0x80004005).</target>       </trans-unit>
        <trans-unit id="104" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Runtime.InteropServices.SEHException">
          <source>The .NET Framework often encounters unmanaged SEH exceptions that are automatically mapped to managed equivalents.</source>
          <target state="translated">.NET Framework는 종종 자동으로 관리 되는 형식에 매핑되는 관리 되지 않는 SEH 예외가 발생 합니다.</target>       </trans-unit>
        <trans-unit id="105" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Runtime.InteropServices.SEHException">
          <source>There are two common unmanaged SEH exceptions:</source>
          <target state="translated">두 가지 일반적인 관리 되지 않는 SEH 예외가 있습니다.</target>       </trans-unit>
        <trans-unit id="106" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Runtime.InteropServices.SEHException">
          <source><ph id="ph1">`STATUS_NO_MEMORY`</ph> exceptions are automatically mapped to the <ph id="ph2">&lt;xref:System.OutOfMemoryException&gt;</ph> class.</source>
          <target state="translated"><ph id="ph1">`STATUS_NO_MEMORY`</ph> 예외는 자동으로 매핑됩니다는 <ph id="ph2">&lt;xref:System.OutOfMemoryException&gt;</ph> 클래스입니다.</target>       </trans-unit>
        <trans-unit id="107" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Runtime.InteropServices.SEHException">
          <source><ph id="ph1">`STATUS_ACCESS_VIOLATION`</ph> exceptions are automatically mapped as follows:</source>
          <target state="translated"><ph id="ph1">`STATUS_ACCESS_VIOLATION`</ph> 예외는 자동으로 다음과 같이 매핑됩니다.</target>       </trans-unit>
        <trans-unit id="108" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Runtime.InteropServices.SEHException">
          <source>If <ph id="ph1">`legacyNullReferencePolicy`</ph> is applied, all access violations are mapped to the <ph id="ph2">&lt;xref:System.NullReferenceException&gt;</ph> class.</source>
          <target state="translated">경우 <ph id="ph1">`legacyNullReferencePolicy`</ph> 은 적용, 모든 액세스 위반에 매핑되는 <ph id="ph2">&lt;xref:System.NullReferenceException&gt;</ph> 클래스입니다.</target>       </trans-unit>
        <trans-unit id="109" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Runtime.InteropServices.SEHException">
          <source>If the address at which the read/write was attempted is not in JIT-compiled code, the exception is mapped to the <ph id="ph1">&lt;xref:System.AccessViolationException&gt;</ph> class.</source>
          <target state="translated">예외는 읽기/쓰기 시도한 주소 JIT 컴파일된 코드에 없는 경우 매핑되는 <ph id="ph1">&lt;xref:System.AccessViolationException&gt;</ph> 클래스입니다.</target>       </trans-unit>
        <trans-unit id="110" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Runtime.InteropServices.SEHException">
          <source>If the address at which the read/write was attempted is in JIT-compiled code, but it is not in the OS Null partition area, the exception is mapped to the <ph id="ph1">&lt;xref:System.AccessViolationException&gt;</ph> class.</source>
          <target state="translated">예외가 JIT로 컴파일된 코드에서 읽기/쓰기를 시도 하 고 주소는 운영 체제 Null 파티션 영역에 표시 되지만 매핑되는 <ph id="ph1">&lt;xref:System.AccessViolationException&gt;</ph> 클래스입니다.</target>       </trans-unit>
        <trans-unit id="111" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Runtime.InteropServices.SEHException">
          <source>If there is no <ph id="ph1">`legacyNullReferencePolicy`</ph>, and the address at which the read/write was attempted is in JIT-compiled code and in the OS Null partition area, the exception is mapped to the <ph id="ph2">&lt;xref:System.NullReferenceException&gt;</ph> class.</source>
          <target state="translated">없을 경우 없습니다 <ph id="ph1">`legacyNullReferencePolicy`</ph>, 및 읽기/쓰기를 시도한 주소가 OS Null 파티션 영역 및 JIT 컴파일된 코드에서 예외 매핑되는 <ph id="ph2">&lt;xref:System.NullReferenceException&gt;</ph> 클래스입니다.</target>       </trans-unit>
        <trans-unit id="112" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Runtime.InteropServices.SEHException">
          <source>Any SEH exception that is not automatically mapped to a specific exception is mapped to the <ph id="ph1">&lt;xref:System.Runtime.InteropServices.SEHException&gt;</ph> class by default.</source>
          <target state="translated">특정 예외에 자동으로 매핑되지 않은 SEH 예외 매핑되는 <ph id="ph1">&lt;xref:System.Runtime.InteropServices.SEHException&gt;</ph> 기본적으로 클래스입니다.</target>       </trans-unit>
        <trans-unit id="113" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Runtime.InteropServices.SEHException">
          <source>For more information, search on "unmanaged exceptions" and "Structured Exception Handling" in the MSDN Library.</source>
          <target state="translated">자세한 내용을 보려면 "관리 되지 않는 예외" 및 "구조적 예외 처리" MSDN Library에서 검색 합니다.</target>       </trans-unit>
        <trans-unit id="114" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Runtime.InteropServices.SEHException">
          <source>Note that the <ph id="ph1">&lt;xref:System.Runtime.InteropServices.SEHException&gt;</ph> class does not cause unmanaged C++ exception destructors to be called.</source>
          <target state="translated"><ph id="ph1">&lt;xref:System.Runtime.InteropServices.SEHException&gt;</ph> 클래스는 관리 되지 않는 c + + 예외가 소멸자를 호출할 수 발생 하지 않습니다.</target>       </trans-unit>
        <trans-unit id="115" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Runtime.InteropServices.SEHException">
          <source>To ensure that unmanaged C++ exception destructors are called, use the following syntax in the <ph id="ph1">`catch`</ph> block.</source>
          <target state="translated">관리 되지 않는 c + + 예외 소멸자가 호출 되도록에서 다음 구문을 사용 하 여는 <ph id="ph1">`catch`</ph> 블록입니다.</target>       </trans-unit>
        <trans-unit id="116" translate="yes" xml:space="preserve" uid="T:System.Runtime.InteropServices.SEHException">
          <source>Initializes a new instance of the <ph id="ph1">&lt;see cref="T:System.Runtime.InteropServices.SEHException" /&gt;</ph> class.</source>
          <target state="translated"><ph id="ph1">&lt;see cref="T:System.Runtime.InteropServices.SEHException" /&gt;</ph> 클래스의 새 인스턴스를 초기화합니다.</target>       </trans-unit>
        <trans-unit id="117" translate="yes" xml:space="preserve" uid="M:System.Runtime.InteropServices.SEHException.#ctor">
          <source>Initializes a new instance of the <ph id="ph1">&lt;see cref="T:System.Runtime.InteropServices.SEHException" /&gt;</ph> class.</source>
          <target state="translated"><ph id="ph1">&lt;see cref="T:System.Runtime.InteropServices.SEHException" /&gt;</ph> 클래스의 새 인스턴스를 초기화합니다.</target>       </trans-unit>
        <trans-unit id="118" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Runtime.InteropServices.SEHException.#ctor">
          <source>The <ph id="ph1">&lt;xref:System.Runtime.InteropServices.SEHException&gt;</ph> class inherits from the <ph id="ph2">&lt;xref:System.Runtime.InteropServices.ExternalException&gt;</ph> class.</source>
          <target state="translated"><ph id="ph1">&lt;xref:System.Runtime.InteropServices.SEHException&gt;</ph> 클래스는 <ph id="ph2">&lt;xref:System.Runtime.InteropServices.ExternalException&gt;</ph> 클래스에서 상속합니다.</target>       </trans-unit>
        <trans-unit id="119" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Runtime.InteropServices.SEHException.#ctor">
          <source>This constructor sets the properties of the <ph id="ph1">&lt;xref:System.Exception&gt;</ph> object to the values in the following table.</source>
          <target state="translated">속성을 설정 하는이 생성자는 <ph id="ph1">&lt;xref:System.Exception&gt;</ph> 개체는 다음 표에 있는 값입니다.</target>       </trans-unit>
        <trans-unit id="120" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Runtime.InteropServices.SEHException.#ctor">
          <source>Property</source>
          <target state="translated">속성</target>       </trans-unit>
        <trans-unit id="121" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Runtime.InteropServices.SEHException.#ctor">
          <source>Value</source>
          <target state="translated">값</target>       </trans-unit>
        <trans-unit id="122" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Runtime.InteropServices.SEHException.#ctor">
          <source>A null reference (<ph id="ph1">`Nothing`</ph> in Visual Basic).</source>
          <target state="translated">null 참조(Visual Basic의 경우 <ph id="ph1">`Nothing`</ph>)</target>       </trans-unit>
        <trans-unit id="123" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Runtime.InteropServices.SEHException.#ctor">
          <source>A localized error message string.</source>
          <target state="translated">지역화 된 오류 메시지 문자열입니다.</target>       </trans-unit>
        <trans-unit id="124" translate="yes" xml:space="preserve" uid="M:System.Runtime.InteropServices.SEHException.#ctor(System.String)">
          <source>The message that indicates the reason for the exception.</source>
          <target state="translated">예외에 대한 이유를 나타내는 메시지입니다.</target>       </trans-unit>
        <trans-unit id="125" translate="yes" xml:space="preserve" uid="M:System.Runtime.InteropServices.SEHException.#ctor(System.String)">
          <source>Initializes a new instance of the <ph id="ph1">&lt;see cref="T:System.Runtime.InteropServices.SEHException" /&gt;</ph> class with a specified message.</source>
          <target state="translated">지정된 메시지를 사용하여 <ph id="ph1">&lt;see cref="T:System.Runtime.InteropServices.SEHException" /&gt;</ph> 클래스의 새 인스턴스를 초기화합니다.</target>       </trans-unit>
        <trans-unit id="126" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Runtime.InteropServices.SEHException.#ctor(System.String)">
          <source><ph id="ph1">&lt;xref:System.Runtime.InteropServices.SEHException&gt;</ph> inherits from <ph id="ph2">&lt;xref:System.Runtime.InteropServices.ExternalException&gt;</ph>.</source>
          <target state="translated"><ph id="ph1">&lt;xref:System.Runtime.InteropServices.SEHException&gt;</ph>는 <ph id="ph2">&lt;xref:System.Runtime.InteropServices.ExternalException&gt;</ph>에서 상속됩니다.</target>       </trans-unit>
        <trans-unit id="127" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Runtime.InteropServices.SEHException.#ctor(System.String)">
          <source>This constructor sets the properties of the <ph id="ph1">&lt;xref:System.Exception&gt;</ph> object as shown in the following table.</source>
          <target state="translated">속성을 설정 하는이 생성자는 <ph id="ph1">&lt;xref:System.Exception&gt;</ph> 다음 표에 나와 있는 것 처럼 개체입니다.</target>       </trans-unit>
        <trans-unit id="128" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Runtime.InteropServices.SEHException.#ctor(System.String)">
          <source>Property</source>
          <target state="translated">속성</target>       </trans-unit>
        <trans-unit id="129" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Runtime.InteropServices.SEHException.#ctor(System.String)">
          <source>Value</source>
          <target state="translated">값</target>       </trans-unit>
        <trans-unit id="130" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Runtime.InteropServices.SEHException.#ctor(System.String)">
          <source>A null reference (<ph id="ph1">`Nothing`</ph> in Visual Basic).</source>
          <target state="translated">null 참조(Visual Basic의 경우 <ph id="ph1">`Nothing`</ph>)</target>       </trans-unit>
        <trans-unit id="131" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Runtime.InteropServices.SEHException.#ctor(System.String)">
          <source><ph id="ph1">`message`</ph>.</source>
          <target state="translated"><ph id="ph1">`message`</ph>.</target>       </trans-unit>
        <trans-unit id="132" translate="yes" xml:space="preserve" uid="M:System.Runtime.InteropServices.SEHException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)">
          <source>The object that holds the serialized object data.</source>
          <target state="translated">serialize된 개체 데이터를 보유하는 개체입니다.</target>       </trans-unit>
        <trans-unit id="133" translate="yes" xml:space="preserve" uid="M:System.Runtime.InteropServices.SEHException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)">
          <source>The contextual information about the source or destination.</source>
          <target state="translated">원본 또는 대상에 대한 컨텍스트 정보입니다.</target>       </trans-unit>
        <trans-unit id="134" translate="yes" xml:space="preserve" uid="M:System.Runtime.InteropServices.SEHException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)">
          <source>Initializes a new instance of the <ph id="ph1">&lt;see cref="T:System.Runtime.InteropServices.SEHException" /&gt;</ph> class from serialization data.</source>
          <target state="translated">serialization 데이터로부터 <ph id="ph1">&lt;see cref="T:System.Runtime.InteropServices.SEHException" /&gt;</ph> 클래스의 새 인스턴스를 초기화합니다.</target>       </trans-unit>
        <trans-unit id="135" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Runtime.InteropServices.SEHException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)">
          <source>This constructor is called during deserialization to reconstitute the exception object transmitted over a stream.</source>
          <target state="translated">이 생성자는 deserialization을 수행하는 동안 호출되어 스트림을 통해 전송된 예외 개체를 다시 구성합니다.</target>       </trans-unit>
        <trans-unit id="136" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Runtime.InteropServices.SEHException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)">
          <source>For more information, see the <ph id="ph1">&lt;xref:System.Runtime.Serialization&gt;</ph> namespace.</source>
          <target state="translated">자세한 내용은 <ph id="ph1">&lt;xref:System.Runtime.Serialization&gt;</ph> 네임스페이스를 참조하세요.</target>       </trans-unit>
        <trans-unit id="137" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Runtime.InteropServices.SEHException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)">
          <source><ph id="ph1">&lt;xref:System.Runtime.InteropServices.SEHException&gt;</ph> inherits from <ph id="ph2">&lt;xref:System.Runtime.InteropServices.ExternalException&gt;</ph>.</source>
          <target state="translated"><ph id="ph1">&lt;xref:System.Runtime.InteropServices.SEHException&gt;</ph>는 <ph id="ph2">&lt;xref:System.Runtime.InteropServices.ExternalException&gt;</ph>에서 상속됩니다.</target>       </trans-unit>
        <trans-unit id="138" translate="yes" xml:space="preserve" uid="M:System.Runtime.InteropServices.SEHException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)">
          <source><ph id="ph1">&lt;paramref name="info" /&gt;</ph> is <ph id="ph2">&lt;see langword="null" /&gt;</ph>.</source>
          <target state="translated"><ph id="ph1">&lt;paramref name="info" /&gt;</ph>가 <ph id="ph2">&lt;see langword="null" /&gt;</ph>인 경우</target>       </trans-unit>
        <trans-unit id="139" translate="yes" xml:space="preserve" uid="M:System.Runtime.InteropServices.SEHException.#ctor(System.String,System.Exception)">
          <source>The error message that explains the reason for the exception.</source>
          <target state="translated">@FSHO2@예외 이유를 설명하는 오류 메시지입니다.</target>       </trans-unit>
        <trans-unit id="140" translate="yes" xml:space="preserve" uid="M:System.Runtime.InteropServices.SEHException.#ctor(System.String,System.Exception)">
          <source>The exception that is the cause of the current exception.</source>
          <target state="translated">현재 예외의 원인인 예외입니다.</target>       </trans-unit>
        <trans-unit id="141" translate="yes" xml:space="preserve" uid="M:System.Runtime.InteropServices.SEHException.#ctor(System.String,System.Exception)">
          <source>If the <bpt id="p1">&lt;c&gt;</bpt>inner<ept id="p1">&lt;/c&gt;</ept> parameter is not <ph id="ph1">&lt;see langword="null" /&gt;</ph>, the current exception is raised in a <ph id="ph2">&lt;see langword="catch" /&gt;</ph> block that handles the inner exception.</source>
          <target state="translated"><bpt id="p1">&lt;c&gt;</bpt>inner<ept id="p1">&lt;/c&gt;</ept> 매개 변수가 <ph id="ph1">&lt;see langword="null" /&gt;</ph>이 아니면 현재 예외는 내부 예외를 처리하는 <ph id="ph2">&lt;see langword="catch" /&gt;</ph> 블록에서 발생합니다.</target>       </trans-unit>
        <trans-unit id="142" translate="yes" xml:space="preserve" uid="M:System.Runtime.InteropServices.SEHException.#ctor(System.String,System.Exception)">
          <source>Initializes a new instance of the <ph id="ph1">&lt;see cref="T:System.Runtime.InteropServices.SEHException" /&gt;</ph> class with a specified error message and a reference to the inner exception that is the cause of this exception.</source>
          <target state="translated">지정된 오류 메시지와 해당 예외의 원인인 내부 예외에 대한 참조를 사용하여 <ph id="ph1">&lt;see cref="T:System.Runtime.InteropServices.SEHException" /&gt;</ph> 클래스의 새 인스턴스를 초기화합니다.</target>       </trans-unit>
        <trans-unit id="143" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Runtime.InteropServices.SEHException.#ctor(System.String,System.Exception)">
          <source>An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <ph id="ph1">&lt;xref:System.Exception.InnerException%2A&gt;</ph> property.</source>
          <target state="translated">이전 예외의 직접적인 결과로 throw되는 예외의 <ph id="ph1">&lt;xref:System.Exception.InnerException%2A&gt;</ph> 속성에는 이전 예외에 대한 참조가 들어 있어야 합니다.</target>       </trans-unit>
        <trans-unit id="144" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Runtime.InteropServices.SEHException.#ctor(System.String,System.Exception)">
          <source>The <ph id="ph1">&lt;xref:System.Exception.InnerException%2A&gt;</ph> property returns the same value that is passed into the constructor, or <ph id="ph2">`null`</ph> if the <ph id="ph3">&lt;xref:System.Exception.InnerException%2A&gt;</ph> property does not supply the inner exception value to the constructor.</source>
          <target state="translated"><ph id="ph1">&lt;xref:System.Exception.InnerException%2A&gt;</ph> 속성은 생성자에 전달되는 값과 동일한 값을 반환하며, <ph id="ph2">`null`</ph> 속성이 생성자에 내부 예외 값을 제공하지 않는 경우에는 <ph id="ph3">&lt;xref:System.Exception.InnerException%2A&gt;</ph>을 반환합니다.</target>       </trans-unit>
        <trans-unit id="145" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Runtime.InteropServices.SEHException.#ctor(System.String,System.Exception)">
          <source>The following table shows the initial property values for an instance of <ph id="ph1">&lt;xref:System.Runtime.InteropServices.SEHException&gt;</ph>.</source>
          <target state="translated">다음 표에서는 <ph id="ph1">&lt;xref:System.Runtime.InteropServices.SEHException&gt;</ph> 인스턴스의 초기 속성 값을 보여 줍니다.</target>       </trans-unit>
        <trans-unit id="146" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Runtime.InteropServices.SEHException.#ctor(System.String,System.Exception)">
          <source>Property</source>
          <target state="translated">속성</target>       </trans-unit>
        <trans-unit id="147" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Runtime.InteropServices.SEHException.#ctor(System.String,System.Exception)">
          <source>Value</source>
          <target state="translated">값</target>       </trans-unit>
        <trans-unit id="148" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Runtime.InteropServices.SEHException.#ctor(System.String,System.Exception)">
          <source>The inner exception reference.</source>
          <target state="translated">내부 예외 참조</target>       </trans-unit>
        <trans-unit id="149" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Runtime.InteropServices.SEHException.#ctor(System.String,System.Exception)">
          <source>The error message string.</source>
          <target state="translated">오류 메시지 문자열</target>       </trans-unit>
        <trans-unit id="150" translate="yes" xml:space="preserve" uid="M:System.Runtime.InteropServices.SEHException.CanResume">
          <source>Indicates whether the exception can be recovered from, and whether the code can continue from the point at which the exception was thrown.</source>
          <target state="translated">예외를 복구할 수 있는지 여부와 예외가 throw된 위치부터 코드를 계속 진행할 수 있는지 여부를 나타냅니다.</target>       </trans-unit>
        <trans-unit id="151" translate="yes" xml:space="preserve" uid="M:System.Runtime.InteropServices.SEHException.CanResume">
          <source>Always <ph id="ph1">&lt;see langword="false" /&gt;</ph>, because resumable exceptions are not implemented.</source>
          <target state="translated">다시 시작할 수 있는 예외가 아직 구현되지 않았으므로 항상 <ph id="ph1">&lt;see langword="false" /&gt;</ph>입니다.</target>       </trans-unit>
        <trans-unit id="152" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Runtime.InteropServices.SEHException.CanResume">
          <source>If <ph id="ph1">&lt;xref:System.Runtime.InteropServices.SEHException.CanResume%2A&gt;</ph> returns <ph id="ph2">`true`</ph>, then a filtered exception handler can correct the problem that caused the exception, and the code will continue from the point at which the exception was thrown.</source>
          <target state="translated">경우 <ph id="ph1">&lt;xref:System.Runtime.InteropServices.SEHException.CanResume%2A&gt;</ph> 반환 <ph id="ph2">`true`</ph>, 필터링된 된 예외 처리기는 예외를 발생 시킨 문제를 해결할 수는 다음 및 코드는 예외가 throw 된 지점부터 계속 됩니다.</target>       </trans-unit>
      </group>
    </body>
  </file>
</xliff>