<?xml version="1.0" encoding="utf-8"?>
<xliff xmlns="urn:oasis:names:tc:xliff:document:1.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.2" xsi:schemaLocation="urn:oasis:names:tc:xliff:document:1.2 xliff-core-1.2-transitional.xsd">
  <file datatype="xml" original="UnhandledExceptionAction.xml" source-language="en-US" target-language="ko-KR">
    <header>
      <tool tool-id="mdxliff" tool-name="mdxliff" tool-version="1.0-15c36f0" tool-company="Microsoft" />
      <xliffext:skl_file_name xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">02cd5861-7ce2-4a82-b358-31f8435a0ac5070ae82d795d2b3a920f23bb6d8e67539cdf87c2.skl</xliffext:skl_file_name>
      <xliffext:version xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">1.2</xliffext:version>
      <xliffext:ms.openlocfilehash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">070ae82d795d2b3a920f23bb6d8e67539cdf87c2</xliffext:ms.openlocfilehash>
      <xliffext:ms.sourcegitcommit xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">d31dc2ede16f6f7bc64e90d9f897ff54c4e3869b</xliffext:ms.sourcegitcommit>
      <xliffext:ms.lasthandoff xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">04/03/2018</xliffext:ms.lasthandoff>
      <xliffext:moniker_ids xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">netframework-4.5.1,netframework-4.5.2,netframework-4.5,netframework-4.6.1,netframework-4.6.2,netframework-4.6,netframework-4.7.1,netframework-4.7</xliffext:moniker_ids>
    </header>
    <body>
      <group id="content" extype="content">
        <trans-unit id="101" translate="yes" xml:space="preserve" uid="T:System.Activities.UnhandledExceptionAction">
          <source>Specifies the action that occurs when an exception escapes the root of a workflow.</source>
          <target state="translated">예외에서 워크플로 루트를 이스케이프할 때 수행되는 동작을 지정합니다.</target>       </trans-unit>
        <trans-unit id="102" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Activities.UnhandledExceptionAction">
          <source>The <ph id="ph1">&lt;xref:System.Activities.WorkflowApplication.OnUnhandledException%2A&gt;</ph> function is invoked if an exception escapes the root of the workflow.</source>
          <target state="translated">예외에서 워크플로 루트를 이스케이프할 때 <ph id="ph1">&lt;xref:System.Activities.WorkflowApplication.OnUnhandledException%2A&gt;</ph> 함수가 호출됩니다.</target>       </trans-unit>
        <trans-unit id="103" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Activities.UnhandledExceptionAction">
          <source>The <ph id="ph1">&lt;xref:System.Activities.WorkflowApplicationUnhandledExceptionEventArgs&gt;</ph> provides access to the exception as well as a pointer to the <ph id="ph2">&lt;xref:System.Activities.Activity&gt;</ph> that generated the exception.</source>
          <target state="translated">The <ph id="ph1">&lt;xref:System.Activities.WorkflowApplicationUnhandledExceptionEventArgs&gt;</ph>는 예외에 대한 액세스는 물론 예외를 생성한 <ph id="ph2">&lt;xref:System.Activities.Activity&gt;</ph>에 대한 포인터를 제공합니다.</target>       </trans-unit>
        <trans-unit id="104" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Activities.UnhandledExceptionAction">
          <source>Terminate is the default action if no <ph id="ph1">&lt;xref:System.Activities.WorkflowApplication.OnUnhandledException%2A&gt;</ph> handler is specified.</source>
          <target state="translated">종료 되지 않은 경우 기본 작업은 <ph id="ph1">&lt;xref:System.Activities.WorkflowApplication.OnUnhandledException%2A&gt;</ph> 처리기 지정 합니다.</target>       </trans-unit>
        <trans-unit id="105" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Activities.UnhandledExceptionAction">
          <source>The following example invokes a workflow that throws an exception.</source>
          <target state="translated">다음 예제에서는 예외를 throw하는 워크플로를 호출합니다.</target>       </trans-unit>
        <trans-unit id="106" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Activities.UnhandledExceptionAction">
          <source>The exception is unhandled by the workflow and the <ph id="ph1">&lt;xref:System.Activities.WorkflowApplication.OnUnhandledException%2A&gt;</ph> handler is invoked.</source>
          <target state="translated">이 예외는 워크플로에서 처리되지 않으며 <ph id="ph1">&lt;xref:System.Activities.WorkflowApplication.OnUnhandledException%2A&gt;</ph> 처리기가 호출됩니다.</target>       </trans-unit>
        <trans-unit id="107" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Activities.UnhandledExceptionAction">
          <source>The <ph id="ph1">&lt;xref:System.Activities.WorkflowApplicationUnhandledExceptionEventArgs&gt;</ph> are inspected to provide information about the exception, and the workflow is terminated.</source>
          <target state="translated"><ph id="ph1">&lt;xref:System.Activities.WorkflowApplicationUnhandledExceptionEventArgs&gt;</ph>를 검사하여 예외에 대한 정보를 제공하고 워크플로가 종료됩니다.</target>       </trans-unit>
        <trans-unit id="108" translate="yes" xml:space="preserve" uid="F:System.Activities.UnhandledExceptionAction.Abort">
          <source>Specifies that the <ph id="ph1">&lt;see cref="T:System.Activities.WorkflowApplication" /&gt;</ph> should abort the workflow.</source>
          <target state="translated"><ph id="ph1">&lt;see cref="T:System.Activities.WorkflowApplication" /&gt;</ph>에서 워크플로를 중단하도록 지정합니다.</target>       </trans-unit>
        <trans-unit id="109" translate="yes" xml:space="preserve" extradata="MT" uid="F:System.Activities.UnhandledExceptionAction.Abort">
          <source>This results in <ph id="ph1">&lt;xref:System.Activities.WorkflowApplication.Aborted%2A&gt;</ph> being called when the abort process is complete.</source>
          <target state="translated">이렇게 하면 중단 프로세스가 완료될 때 <ph id="ph1">&lt;xref:System.Activities.WorkflowApplication.Aborted%2A&gt;</ph>가 호출됩니다.</target>       </trans-unit>
        <trans-unit id="110" translate="yes" xml:space="preserve" extradata="MT" uid="F:System.Activities.UnhandledExceptionAction.Abort">
          <source>The unhandled exception is used as the abort reason.</source>
          <target state="translated">처리되지 않은 예외가 중단 이유로 사용됩니다.</target>       </trans-unit>
        <trans-unit id="111" translate="yes" xml:space="preserve" extradata="MT" uid="F:System.Activities.UnhandledExceptionAction.Abort">
          <source>The following example invokes a workflow that throws an exception.</source>
          <target state="translated">다음 예제에서는 예외를 throw하는 워크플로를 호출합니다.</target>       </trans-unit>
        <trans-unit id="112" translate="yes" xml:space="preserve" extradata="MT" uid="F:System.Activities.UnhandledExceptionAction.Abort">
          <source>The exception is unhandled by the workflow and the <ph id="ph1">&lt;xref:System.Activities.WorkflowApplication.OnUnhandledException%2A&gt;</ph> handler is invoked.</source>
          <target state="translated">이 예외는 워크플로에서 처리되지 않으며 <ph id="ph1">&lt;xref:System.Activities.WorkflowApplication.OnUnhandledException%2A&gt;</ph> 처리기가 호출됩니다.</target>       </trans-unit>
        <trans-unit id="113" translate="yes" xml:space="preserve" extradata="MT" uid="F:System.Activities.UnhandledExceptionAction.Abort">
          <source>The <ph id="ph1">&lt;xref:System.Activities.WorkflowApplicationUnhandledExceptionEventArgs&gt;</ph> are inspected to provide information about the exception, and the workflow is aborted.</source>
          <target state="translated">예외에 대한 정보를 제공하기 위해 <ph id="ph1">&lt;xref:System.Activities.WorkflowApplicationUnhandledExceptionEventArgs&gt;</ph>가 검사되며 워크플로가 중단됩니다.</target>       </trans-unit>
        <trans-unit id="114" translate="yes" xml:space="preserve" uid="F:System.Activities.UnhandledExceptionAction.Cancel">
          <source>Specifies that the <ph id="ph1">&lt;see cref="T:System.Activities.WorkflowApplication" /&gt;</ph> should schedule the cancellation of the root activity and resume execution.</source>
          <target state="translated"><ph id="ph1">&lt;see cref="T:System.Activities.WorkflowApplication" /&gt;</ph>에서 루트 활동 취소를 예약하고 실행을 다시 시작하도록 지정합니다.</target>       </trans-unit>
        <trans-unit id="115" translate="yes" xml:space="preserve" extradata="MT" uid="F:System.Activities.UnhandledExceptionAction.Cancel">
          <source>This results in <ph id="ph1">&lt;xref:System.Activities.WorkflowApplication.Completed%2A&gt;</ph> being called when the cancellation process is complete.</source>
          <target state="translated">이렇게 하면 취소 프로세스가 완료될 때 <ph id="ph1">&lt;xref:System.Activities.WorkflowApplication.Completed%2A&gt;</ph>가 호출됩니다.</target>       </trans-unit>
        <trans-unit id="116" translate="yes" xml:space="preserve" extradata="MT" uid="F:System.Activities.UnhandledExceptionAction.Cancel">
          <source>The following example invokes a workflow that throws an exception.</source>
          <target state="translated">다음 예제에서는 예외를 throw하는 워크플로를 호출합니다.</target>       </trans-unit>
        <trans-unit id="117" translate="yes" xml:space="preserve" extradata="MT" uid="F:System.Activities.UnhandledExceptionAction.Cancel">
          <source>The exception is unhandled by the workflow and the <ph id="ph1">&lt;xref:System.Activities.WorkflowApplication.OnUnhandledException%2A&gt;</ph> handler is invoked.</source>
          <target state="translated">이 예외는 워크플로에서 처리되지 않으며 <ph id="ph1">&lt;xref:System.Activities.WorkflowApplication.OnUnhandledException%2A&gt;</ph> 처리기가 호출됩니다.</target>       </trans-unit>
        <trans-unit id="118" translate="yes" xml:space="preserve" extradata="MT" uid="F:System.Activities.UnhandledExceptionAction.Cancel">
          <source>The <ph id="ph1">&lt;xref:System.Activities.WorkflowApplicationUnhandledExceptionEventArgs&gt;</ph> are inspected to provide information about the exception, and the workflow is cancelled.</source>
          <target state="translated">예외에 대한 정보를 제공하기 위해 <ph id="ph1">&lt;xref:System.Activities.WorkflowApplicationUnhandledExceptionEventArgs&gt;</ph>가 검사되며 워크플로가 취소됩니다.</target>       </trans-unit>
        <trans-unit id="119" translate="yes" xml:space="preserve" uid="F:System.Activities.UnhandledExceptionAction.Terminate">
          <source>Specifies that the <ph id="ph1">&lt;see cref="T:System.Activities.WorkflowApplication" /&gt;</ph> should schedule termination of the root activity and resume execution.</source>
          <target state="translated"><ph id="ph1">&lt;see cref="T:System.Activities.WorkflowApplication" /&gt;</ph>에서 루트 활동 종료를 예약하고 실행을 다시 시작하도록 지정합니다.</target>       </trans-unit>
        <trans-unit id="120" translate="yes" xml:space="preserve" extradata="MT" uid="F:System.Activities.UnhandledExceptionAction.Terminate">
          <source>This results in <ph id="ph1">&lt;xref:System.Activities.WorkflowApplication.Completed%2A&gt;</ph> being called when the termination process is complete.</source>
          <target state="translated">이렇게 하면 종료 프로세스가 완료될 때 <ph id="ph1">&lt;xref:System.Activities.WorkflowApplication.Completed%2A&gt;</ph>가 호출됩니다.</target>       </trans-unit>
        <trans-unit id="121" translate="yes" xml:space="preserve" extradata="MT" uid="F:System.Activities.UnhandledExceptionAction.Terminate">
          <source>The unhandled exception is used as the termination reason.</source>
          <target state="translated">처리되지 않은 예외가 종료 이유로 사용됩니다.</target>       </trans-unit>
        <trans-unit id="122" translate="yes" xml:space="preserve" extradata="MT" uid="F:System.Activities.UnhandledExceptionAction.Terminate">
          <source>Terminate is the default action if no <ph id="ph1">&lt;xref:System.Activities.WorkflowApplication.OnUnhandledException%2A&gt;</ph> handler is specified.</source>
          <target state="translated">종료 되지 않은 경우 기본 작업은 <ph id="ph1">&lt;xref:System.Activities.WorkflowApplication.OnUnhandledException%2A&gt;</ph> 처리기 지정 합니다.</target>       </trans-unit>
        <trans-unit id="123" translate="yes" xml:space="preserve" extradata="MT" uid="F:System.Activities.UnhandledExceptionAction.Terminate">
          <source>The following example invokes a workflow that throws an exception.</source>
          <target state="translated">다음 예제에서는 예외를 throw하는 워크플로를 호출합니다.</target>       </trans-unit>
        <trans-unit id="124" translate="yes" xml:space="preserve" extradata="MT" uid="F:System.Activities.UnhandledExceptionAction.Terminate">
          <source>The exception is unhandled by the workflow and the <ph id="ph1">&lt;xref:System.Activities.WorkflowApplication.OnUnhandledException%2A&gt;</ph> handler is invoked.</source>
          <target state="translated">이 예외는 워크플로에서 처리되지 않으며 <ph id="ph1">&lt;xref:System.Activities.WorkflowApplication.OnUnhandledException%2A&gt;</ph> 처리기가 호출됩니다.</target>       </trans-unit>
        <trans-unit id="125" translate="yes" xml:space="preserve" extradata="MT" uid="F:System.Activities.UnhandledExceptionAction.Terminate">
          <source>The <ph id="ph1">&lt;xref:System.Activities.WorkflowApplicationUnhandledExceptionEventArgs&gt;</ph> are inspected to provide information about the exception, and the workflow is terminated.</source>
          <target state="translated"><ph id="ph1">&lt;xref:System.Activities.WorkflowApplicationUnhandledExceptionEventArgs&gt;</ph>를 검사하여 예외에 대한 정보를 제공하고 워크플로가 종료됩니다.</target>       </trans-unit>
      </group>
    </body>
  </file>
</xliff>