<?xml version="1.0" encoding="utf-8"?>
<xliff xmlns="urn:oasis:names:tc:xliff:document:1.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.2" xsi:schemaLocation="urn:oasis:names:tc:xliff:document:1.2 xliff-core-1.2-transitional.xsd">
  <file datatype="xml" original="XamlInternalException.xml" source-language="en-US" target-language="ko-KR">
    <header>
      <tool tool-id="mdxliff" tool-name="mdxliff" tool-version="1.0-15c36f0" tool-company="Microsoft" />
      <xliffext:skl_file_name xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">02cd5861-7ce2-4a82-b358-31f8435a0ac50729fa9645baf6a20d37770d139f103712c6612f.skl</xliffext:skl_file_name>
      <xliffext:version xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">1.2</xliffext:version>
      <xliffext:ms.openlocfilehash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">0729fa9645baf6a20d37770d139f103712c6612f</xliffext:ms.openlocfilehash>
      <xliffext:ms.sourcegitcommit xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">d31dc2ede16f6f7bc64e90d9f897ff54c4e3869b</xliffext:ms.sourcegitcommit>
      <xliffext:ms.lasthandoff xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">04/03/2018</xliffext:ms.lasthandoff>
      <xliffext:moniker_ids xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">netframework-4.5.1,netframework-4.5.2,netframework-4.5,netframework-4.6.1,netframework-4.6.2,netframework-4.6,netframework-4.7.1,netframework-4.7</xliffext:moniker_ids>
    </header>
    <body>
      <group id="content" extype="content">
        <trans-unit id="101" translate="yes" xml:space="preserve" uid="T:System.Xaml.XamlInternalException">
          <source>The exception that is thrown for internal inconsistencies that occur during XAML reading and XAML writing.</source>
          
        </trans-unit>
        <trans-unit id="102" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Xaml.XamlInternalException">
          <source>This exception is usually thrown only when some aspect of the XAML reader or XAML writer system was extended by your code, and inconsistencies or implementation problems occurred that were passed on to the .NET Framework XAML Services system code.</source>
          <target state="translated">이 예외는 대개 XAML 판독기 또는 XAML 작성기 시스템의 일부 측면 코드에 의해 확장 된.NET Framework XAML 서비스 시스템 코드 전달 된 불일치나 구현 문제가 발생 한 경우에 throw 됩니다.</target>       </trans-unit>
        <trans-unit id="103" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Xaml.XamlInternalException">
          <source>Exceptions that might originate from third parties, such as parsing XAML and encountering errors in the XAML, should not throw <ph id="ph1">&lt;xref:System.Xaml.XamlInternalException&gt;</ph>, and should instead throw other exceptions such as <ph id="ph2">&lt;xref:System.Xaml.XamlParseException&gt;</ph> or <ph id="ph3">&lt;xref:System.Xaml.XamlObjectWriterException&gt;</ph>.</source>
          <target state="translated">XAML을 구문 분석 하는 XAML에 오류가 발생 한 등의 제 3 자에서 문제가 발생 한 예외를 throw 해서는 안 <ph id="ph1">&lt;xref:System.Xaml.XamlInternalException&gt;</ph>, 해야 대신와 같은 다른 예외를 throw 하 고 <ph id="ph2">&lt;xref:System.Xaml.XamlParseException&gt;</ph> 또는 <ph id="ph3">&lt;xref:System.Xaml.XamlObjectWriterException&gt;</ph>합니다.</target>       </trans-unit>
        <trans-unit id="104" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Xaml.XamlInternalException">
          <source>If you are writing code that extends .NET Framework XAML Services, in particular, if you are writing code for a XAML reader or XAML writer implementation, you should maintain this distinction between <ph id="ph1">&lt;xref:System.Xaml.XamlInternalException&gt;</ph> and the other XAML-related exceptions.</source>
          <target state="translated">.NET Framework XAML 서비스를 확장 하는 코드를 작성 하는 경우 특히, XAML 판독기 또는 XAML 작성기 구현에 대 한 코드를 작성 하는 경우 유지 관리 해야 이러한 구분 <ph id="ph1">&lt;xref:System.Xaml.XamlInternalException&gt;</ph> 및 다른 XAML 관련 예외입니다.</target>       </trans-unit>
        <trans-unit id="105" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Xaml.XamlInternalException">
          <source>Your code should only throw <ph id="ph1">&lt;xref:System.Xaml.XamlInternalException&gt;</ph> in cases where further extension of your class violates some design principle or implementation pattern that your callable code defines.</source>
          <target state="translated">코드 throw 해야 <ph id="ph1">&lt;xref:System.Xaml.XamlInternalException&gt;</ph> 클래스의 추가 확장이 호출 가능한 코드를 정의 하는 몇 가지 디자인 원칙 또는 구현 패턴을 위반 하는 경우에서.</target>       </trans-unit>
        <trans-unit id="106" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Xaml.XamlInternalException">
          <source>Your code should throw other XAML-specific exceptions for exception cases where your XAML reader or XAML writer implementation is used without extension and is used to load third-party XAML, third-party XAML schema context, and so on.</source>
          <target state="translated">코드는 XAML 판독기 또는 XAML 작성기 구현의 확장명 없이 사용 하 고 제 3 자 XAML, 제 3 자 XAML 스키마 컨텍스트 등에 로드 하는 데 사용 되 있는 예외 사례에 대 한 다른 XAML 관련 예외를 throw 해야 합니다.</target>       </trans-unit>
        <trans-unit id="107" translate="yes" xml:space="preserve" uid="T:System.Xaml.XamlInternalException">
          <source>Initializes a new instance of the <ph id="ph1">&lt;see cref="T:System.Xaml.XamlInternalException" /&gt;</ph> class.</source>
          
        </trans-unit>
        <trans-unit id="108" translate="yes" xml:space="preserve" uid="M:System.Xaml.XamlInternalException.#ctor">
          <source>Initializes a new instance of the <ph id="ph1">&lt;see cref="T:System.Xaml.XamlInternalException" /&gt;</ph> class with a system-supplied message that describes the error.</source>
          
        </trans-unit>
        <trans-unit id="109" translate="yes" xml:space="preserve" uid="M:System.Xaml.XamlInternalException.#ctor(System.String)">
          <source>The message that describes the exception.</source>
          
        </trans-unit>
        <trans-unit id="110" translate="yes" xml:space="preserve" uid="M:System.Xaml.XamlInternalException.#ctor(System.String)">
          <source>Initializes a new instance of the <ph id="ph1">&lt;see cref="T:System.Xaml.XamlInternalException" /&gt;</ph> class with a specified message that describes the error.</source>
          
        </trans-unit>
        <trans-unit id="111" translate="yes" xml:space="preserve" uid="M:System.Xaml.XamlInternalException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)">
          <source>The object that holds the serialized object data.</source>
          
        </trans-unit>
        <trans-unit id="112" translate="yes" xml:space="preserve" uid="M:System.Xaml.XamlInternalException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)">
          <source>The contextual information about the source or destination.</source>
          
        </trans-unit>
        <trans-unit id="113" translate="yes" xml:space="preserve" uid="M:System.Xaml.XamlInternalException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)">
          <source>Initializes a new instance of the <ph id="ph1">&lt;see cref="T:System.Xaml.XamlInternalException" /&gt;</ph> class with serialized data.</source>
          
        </trans-unit>
        <trans-unit id="114" translate="yes" xml:space="preserve" uid="M:System.Xaml.XamlInternalException.#ctor(System.String,System.Exception)">
          <source>The message that describes the exception.</source>
          
        </trans-unit>
        <trans-unit id="115" translate="yes" xml:space="preserve" uid="M:System.Xaml.XamlInternalException.#ctor(System.String,System.Exception)">
          <source>The exception that is the cause of the current exception.</source>
          
        </trans-unit>
        <trans-unit id="116" translate="yes" xml:space="preserve" uid="M:System.Xaml.XamlInternalException.#ctor(System.String,System.Exception)">
          <source>If the <bpt id="p1">&lt;c&gt;</bpt>innerException<ept id="p1">&lt;/c&gt;</ept> parameter is not <ph id="ph1">&lt;see langword="null" /&gt;</ph>, the current exception is raised in a <ph id="ph2">&lt;see langword="catch" /&gt;</ph> block that handles the inner exception.</source>
          
        </trans-unit>
        <trans-unit id="117" translate="yes" xml:space="preserve" uid="M:System.Xaml.XamlInternalException.#ctor(System.String,System.Exception)">
          <source>Initializes a new instance of the <ph id="ph1">&lt;see cref="T:System.Xaml.XamlInternalException" /&gt;</ph> class with a specified error message and a reference to the inner exception that is the cause of this exception.</source>
          
        </trans-unit>
      </group>
    </body>
  </file>
</xliff>